/*
 * Copyright (c) 2020 Espressif Systems (Shanghai) Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "esp_wifi_types.h"

typedef enum {
    ESP32_WIFI_EVENT_WIFI_READY = WIFI_EVENT_WIFI_READY,
    ESP32_WIFI_EVENT_SCAN_DONE = WIFI_EVENT_SCAN_DONE,
    ESP32_WIFI_EVENT_STA_START = WIFI_EVENT_STA_START,
    ESP32_WIFI_EVENT_STA_STOP = WIFI_EVENT_STA_STOP,
    ESP32_WIFI_EVENT_STA_CONNECTED = WIFI_EVENT_STA_CONNECTED,
    ESP32_WIFI_EVENT_STA_DISCONNECTED = WIFI_EVENT_STA_DISCONNECTED,
    ESP32_WIFI_EVENT_STA_AUTHMODE_CHANGE = WIFI_EVENT_STA_AUTHMODE_CHANGE,

    ESP32_WIFI_EVENT_STA_WPS_ER_SUCCESS = WIFI_EVENT_STA_WPS_ER_SUCCESS,
    ESP32_WIFI_EVENT_STA_WPS_ER_FAILED = WIFI_EVENT_STA_WPS_ER_FAILED,
    ESP32_WIFI_EVENT_STA_WPS_ER_TIMEOUT = WIFI_EVENT_STA_WPS_ER_TIMEOUT,
    ESP32_WIFI_EVENT_STA_WPS_ER_PIN = WIFI_EVENT_STA_WPS_ER_PIN,
    ESP32_WIFI_EVENT_STA_WPS_ER_PBC_OVERLAP = WIFI_EVENT_STA_WPS_ER_PBC_OVERLAP,

    ESP32_WIFI_EVENT_AP_START = WIFI_EVENT_AP_START,
    ESP32_WIFI_EVENT_AP_STOP = WIFI_EVENT_AP_STOP,
    ESP32_WIFI_EVENT_AP_STACONNECTED = WIFI_EVENT_AP_STACONNECTED,
    ESP32_WIFI_EVENT_AP_STADISCONNECTED = WIFI_EVENT_AP_STADISCONNECTED,
    ESP32_WIFI_EVENT_AP_PROBEREQRECVED = WIFI_EVENT_AP_PROBEREQRECVED,

    ESP32_WIFI_EVENT_MAX = WIFI_EVENT_MAX
} esp_wifi_event_t;
