# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/spi_flash/test_apps/esp_flash:
  disable:
    - if: IDF_TARGET == "esp32c6" or IDF_TARGET == "esp32h2"
      temporary: true
      reason: target esp32c6 cannot pass atomic build, target esp32h2 currently doesn't support GPSPI.

components/spi_flash/test_apps/esp_flash_stress:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s2", "esp32s3"]
      temporary: true
      reason: all targets according to the README file

components/spi_flash/test_apps/flash_encryption:
  disable_test:
    - if: IDF_TARGET in ["esp32c2", "esp32s2", "esp32c6", "esp32h2"]
      temporary: true
      reason: No runners # IDF-5634
