# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/spi_flash/test_apps/esp_flash:
  disable:
    - if: IDF_TARGET == "esp32c6" or IDF_TARGET == "esp32h2"
      temporary: true
      reason: target esp32c6 cannot pass atomic build, target esp32h2 currently doesn't support GPSPI.

components/spi_flash/test_apps/esp_flash_stress:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s2", "esp32s3"]
      temporary: true
      reason: all targets according to the README file

components/spi_flash/test_apps/flash_encryption:
  disable_test:
    - if: IDF_TARGET in ["esp32c2", "esp32s2", "esp32c6", "esp32h2"]
      temporary: true
      reason: No runners # IDF-5634

components/spi_flash/test_apps/flash_mmap:
  depends_components:
    - esp_mm
    - spi_flash
  enable:
    - if: CONFIG_NAME in ["release", "rom_impl"] and IDF_TARGET != "linux"
    - if: CONFIG_NAME == "xip_psram" and IDF_TARGET in ["esp32s2", "esp32s3"]
    # S2 doesn't have ROM for flash
    - if: CONFIG_NAME == "xip_psram_with_rom_impl" and IDF_TARGET in ["esp32s3"]
